# Generated by Django 5.2.17 on 2026-09-28 17:16

import apps.videos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yt_channels', '0002_channel_avatar_channel_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=apps.videos.models.generate_video_id, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('video_file', models.FileField(upload_to=apps.videos.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, upload_to=apps.videos.models.video_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='yt_channels.channel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
