# Generated by Django 5.2.17 on 2026-09-27 17:11

import apps.channels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.channels.models.channel_image_path),
        ),
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, upload_to=apps.channels.models.channel_image_path),
        ),
    ]
